name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 */24 * * *"

  workflow_dispatch:

jobs:
  build:
    name: Generate 3D graph
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: nithya-6126

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Generate 3D contribution graph"
          git push
